{
    'name': 'TravelPro ERP',
    'version': '16.0.1.0',
    'summary': 'Agence de Voyage - Réservations, Crédit, Caisse, Factures',
    'category': 'Sales/Travel',
    'author': 'Ton Agence',
    'website': 'https://tonagence.com',
    'license': 'OPL-1',
    'depends': [
        'base',
        'sale',
        'account',
        'purchase',
        'point_of_sale',
        'mail',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'data/pos_config.xml',
        'views/company_views.xml',
        'views/member_views.xml',
        'views/supplier_views.xml',
        'views/reservation_views.xml',
        'views/service_views.xml',
        'views/travel_views.xml',
        'views/credit_views.xml',
        'views/purchase_views.xml',
        'views/invoice_views.xml',
        'views/pos_views.xml',
        'views/invoice_client_views.xml',
        'views/withholding_views.xml',
        'views/purchase_travel_views.xml',
        'views/purchase_report_views.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}