{
    'name': 'TravelPro',
    'version': '1.0',
    'summary': 'Gestion de réservations de voyages',
    'depends': ['base', 'sale', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'views/menu.xml',
        'views/company_views.xml',
        'views/member_views.xml',
        'views/travel_views.xml',
        'views/service_views.xml',
        'views/reservation_views.xml',
        'views/credit_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}